variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: greenaddress/ci@sha256:48e8d7976e3b1f94dc863ac4d5029f762d84eb3214fa9d819e3e2f2302a94f39

bionic_release:
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/bionic_deps.sh
    - ./tools/builddeps.sh
  cache:
    key: build-cache
    paths:
    - build-linux-gcc/gdk-*/src/include/gdk.h
    - build-linux-gcc/gdk-*/build.done
    - build-linux-gcc/gdk-*/src/build-*/src/libgreenaddress_full.a
    - build-linux-gcc/qt-release*
  artifacts:
    expire_in: 1 day
    when: always
    paths:
    - build-linux-gcc/qt-release*/build.log
    - build-linux-gcc/gdk-*/build.log
    - build-linux-gcc/Green

windows_release:
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/bionic_deps.sh
    - ./tools/builddeps.sh windows
  cache:
    key: build-cache
    paths:
    - build-mingw-w64/gdk-*/src/include/gdk.h
    - build-mingw-w64/gdk-*/build.done
    - build-mingw-w64/gdk-*/src/build-*/src/libgreenaddress_full.a
    - build-mingw-w64/qt-release*
  artifacts:
    expire_in: 1 day
    when: always
    paths:
    - build-mingw-w64/qt-release*/build.log
    - build-mingw-w64/gdk-*/build.log
    - build-mingw-w64/release/Green.exe

osx_release:
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/builddeps.sh osx
  cache:
    key: build-cache
    paths:
    - build-osx-clang/gdk-*/src/include/gdk.h
    - build-osx-clang/gdk-*/build.done
    - build-osx-clang/gdk-*/src/build-*/src/libgreenaddress.a
    - build-osx-clang/qt-release*
  artifacts:
    expire_in: 1 day
    when: always
    paths:
    - build-osx-clang/qt-release*/build.log
    - build-osx-clang/gdk-*/build.log
    - build-osx-clang/Green.app
