variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: greenaddress/ci@sha256:ed3188d0d681460f37bfd3f52b3df4c4727c0aba0a90d4545de8cef17c9eef39

stages:
  - build
  - signosx
  - deploy

bionic_release:
  tags:
    - ga
  stage: build
  script:
    - ./tools/bionic_deps.sh
    - ./tools/builddeps.sh linux
  cache:
    key: build-cache
    paths:
    - build-linux-gcc/gdk-*/src/include/gdk.h
    - build-linux-gcc/gdk-*/build.done
    - build-linux-gcc/gdk-*/src/build-*/src/libgreenaddress_full.a
    - build-linux-gcc/qt-release*
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: always
    paths:
    - build-linux-gcc/qt-release*/build.log
    - build-linux-gcc/gdk-*/build.log
    - build-linux-gcc/Green
    - build-linux-gcc/Green-x86_64.AppImage

windows_release:
  tags:
    - ga
  stage: build
  script:
    - ./tools/bionic_deps.sh
    - ./tools/builddeps.sh windows
  cache:
    key: build-cache-windows
    paths:
    - build-mingw-w64/gdk-*/src/include/gdk.h
    - build-mingw-w64/gdk-*/build.done
    - build-mingw-w64/gdk-*/src/build-*/src/libgreenaddress_full.a
    - build-mingw-w64/qt-release*
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: always
    paths:
    - build-mingw-w64/qt-release*/build.log
    - build-mingw-w64/gdk-*/build.log
    - build-mingw-w64/release/Green.exe

osx_release:
  tags:
    - osx
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/builddeps.sh osx
  cache:
    key: build-cache-osx
    paths:
    - build-osx-clang/gdk-*/src/include/gdk.h
    - build-osx-clang/gdk-*/build.done
    - build-osx-clang/gdk-*/src/build-*/src/libgreenaddress_full.a
    - build-osx-clang/qt-release*
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: always
    paths:
    - build-osx-clang/qt-release*/build.log
    - build-osx-clang/gdk-*/build.log
    - build-osx-clang/Green.app

bionic_allsymbolsunstripped_manual:
  extends: bionic_release
  stage: build
  when: manual
  script:
    - ./tools/bionic_deps.sh
    - ./tools/builddeps.sh linux allsymbolsunstripped

osx_allsymbolsunstripped_manual:
  extends: osx_release
  stage: build
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/builddeps.sh osx allsymbolsunstripped

windows_allsymbolsunstripped_manual:
  extends: windows_release
  stage: build
  when: manual
  script:
    - ./tools/bionic_deps.sh
    - ./tools/builddeps.sh windows allsymbolsunstripped

osx_sign:
  tags:
    - osxsigner
  stage: signosx
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: always
    paths:
    - build-osx-clang/Green.app
  dependencies:
    - osx_release
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/osxsign.sh

package_release:
  tags:
    - garelease
  stage: deploy
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
    - $CI_PROJECT_DIR/green_qt_dist
    when: on_success
  script:
    - cd $CI_PROJECT_DIR
    - rm -fr green_qt_dist
    - mkdir green_qt_dist
    - zip -j green_qt_dist/GreenQt_Windows_x86_64.zip build-mingw-w64/release/Green.exe
    - (cd build-osx-clang; zip -r ../green_qt_dist/GreenQt_MacOSX_x86_64.zip Green.app)
    - chmod +x build-linux-gcc/Green
    - tar czf green_qt_dist/GreenQt_Linux_x86_64.tar.gz -C build-linux-gcc Green
    - tar czf green_qt_dist/GreenQt_AppImage_x86_64.tar.gz -C build-linux-gcc Green-x86_64.AppImage
    - cd green_qt_dist
    - /opt/process_release
  dependencies:
    - bionic_release
    - osx_sign
    - windows_release
