language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: travis_wait 30 docker run -v $PWD:/ga greenaddress/ci@sha256:ed3188d0d681460f37bfd3f52b3df4c4727c0aba0a90d4545de8cef17c9eef39 /bin/sh -c "cd /ga && tools/bionic_deps.sh && ./tools/builddeps.sh"
