language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: travis_wait 30 docker run -v $PWD:/ga greenaddress/ci@sha256:99517015c58201ecc351b503870dd3c5dc0e6e83e8e1e21ca9f84912d14de5b5 /bin/sh -c "cd /ga && tools/bionic_deps.sh && ./tools/builddeps.sh"
