language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: travis_wait 30 docker run -v $PWD:/ga greenaddress/ci@sha256:628fab4b831bfb9fa4fd2c2f43282e8b4045fbd0d529311adece22660ab3fd40 /bin/sh -c "cd /ga && tools/bionic_deps.sh && ./tools/builddeps.sh"
